### ISSUE TITLE
Bug - initial load of board editor has drawing mode enabled but the button says otherwise.

### ISSUE THREAD

**Issue by joe-riley** [joe-riley/collaborative-whiteboard#24]
Looks like the toggle and or the initial state of isDrawingMode is reversed but only on initial load of the page.

Steps to reproduce:
1. Load the page
2. Notice that the button says cancel drawing mode
3. Try to draw in the board area and see that you cannot 
4. click on cancel drawing mode and see that the button does not visibly change
5. try to draw in the board area and see that you can now.
6. Clicking the cancel drawing mode button toggles the button now.

please see video https://drive.google.com/file/d/1oDcejQP3lIBVKExa5wbqNlc6veOUIYHT/view

**Comment by kristinmoon** [comment]
Done during class today!
