### ISSUE TITLE
deploy to heroku

### ISSUE THREAD

**Issue by kristinmoon** [joe-riley/collaborative-whiteboard#37]

**Comment by Zapblumar** [comment]
so is this something that needs to be merged or is it just out there now?

**Comment by joe-riley** [comment]
> so is this something that needs to be merged or is it just out there now?

I think this is the ticket to do that work.

**Comment by kristinmoon** [comment]
So will we all have different heroku links? Both Joe and Tylor have separate links... I would assume that we only need one that is pushed off of the master, but we don't have a final master branch.
